# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_trip_departure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='trip',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to='userprofile.UserTrip', verbose_name='Trip Information'),
        ),
        migrations.AddField(
            model_name='usertrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrip', to='userprofile.Trip'),
        ),
    ]
