# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20160911_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagecountry',
            old_name='language1',
            new_name='language',
        ),
    ]
