# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20160911_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_country',
            field=models.ManyToManyField(blank=True, null=True, related_name='userprofile', to='userprofile.LanguageCountry', verbose_name='Language Country Information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trip',
            field=models.ManyToManyField(blank=True, related_name='userprofile', to='userprofile.UserTrip', verbose_name='Trip Information'),
        ),
    ]
