# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_remove_languagecountry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecountry',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
