# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20161012_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecountry',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
