# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20161012_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='trip_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
