# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_usertrip_trip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_country',
        ),
        migrations.AddField(
            model_name='usertrip',
            name='language_country',
            field=models.ManyToManyField(blank=True, null=True, related_name='usertrip', to='userprofile.LanguageCountry', verbose_name='Language Country Information'),
        ),
    ]
