# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20161221_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
