# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_usertrip_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='xp',
        ),
    ]
