# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_remove_usertrip_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
