# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 02:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_auto_20170107_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='xp_track',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
