# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_usertrip_xp_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrip',
            name='xp_track',
        ),
        migrations.AddField(
            model_name='usertrip',
            name='xp_possible',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
