# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-31 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_auto_20170124_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='xp_earned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
