# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160904_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
