# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160904_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=60, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='languagecountry',
            name='language',
        ),
        migrations.AlterField(
            model_name='user',
            name='language_country',
            field=models.ManyToManyField(related_name='userprofile', to='userprofile.LanguageCountry', verbose_name='Language Country Information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trip',
            field=models.ManyToManyField(related_name='userprofile', to='userprofile.UserTrip', verbose_name='Trip Information'),
        ),
        migrations.AddField(
            model_name='languagecountry',
            name='language1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languagecountry', to='userprofile.Language'),
        ),
    ]
